#!/bin/bash
#Разница между $* и $@ в цикле for.

count=1
for param in "$*"
do
	echo "\$* Параметр #$count = $param"
	count=$(( $count + 1 ))
done

count=1
for param in "$@"
do
	echo "\$@ Параметр #$count = $param"
	count=$(( $count + 1))
done
